image: node:20

stages:
  - install
  - lint
  - test
  - build
  - deploy

install:
  stage: install
  script: 
    - npm i
  artifacts:
    paths:
      - node_modules/
      - package-lock.json

lint:
  stage: lint
  script:
    - npm run lint
  dependencies:
    - install

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install

build:
  stage: build
  script:
    - npm run build
  dependencies:
    - install
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying to GitLab Pages"
  dependencies:
    - build
  artifacts:
    paths:
      - public
